include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedSARSA8State -cp $(classPath) HelicopterAgentTileCodedSARSA8State.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedSARSA8State/*
