include ../Makefile.classPath

agentName=SARSA9State
all:
	mkdir -p ../../../../bin/HelicopterAgentTileCoded$(agentName)
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCoded$(agentName) -cp $(classPath) HelicopterAgentTileCoded$(agentName).java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCoded$(agentName)/*
