RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 5 -d ../../../bin/HelicopterAgentQDiscretised -cp $(RLVizPath)/RLVizLib.jar HelicopterAgentQDiscretised.java ../HelicopterAgentQ/HelicopterAgentQ.java ../HelicopterQTable.java


clean:
	rm -Rf ../../../bin/HelicopterAgentQDiscretised/*
