package HSProject.tileCoded.helicopterAgentTileCodedQGaussian;

import org.rlcommunity.rlglue.codec.types.Action;
import org.rlcommunity.rlglue.codec.types.Observation;
import org.rlcommunity.rlglue.codec.util.AgentLoader;

import HSProject.tileCoded.TileCodedAgentQ;

/**
 * An experiment implementing Q-Learning. The random actions are selected with a
 * normal distribution around 0 rather than a uniform distribution.
 * 
 * @author harrison
 *
 */
public class HelicopterAgentTileCodedQGaussian extends TileCodedAgentQ {
	private double gaussianWidth;

	public HelicopterAgentTileCodedQGaussian() {

		int numTiles = getConfig().getInt("stateTiles");
		int numVariables = 12;
		int numTilings = getConfig().getInt("stateTilings");
		double[] statesMin = { -5, -5, -5, -20, -20, -20, -12.566, -12.566, -12.566, -1, -1, -1 };
		double[] statesMax = { 5, 5, 5, 20, 20, 20, 12.566, 12.566, 12.566, 1, 1, 1 };

		initialiseStateTiling(numVariables, statesMin, statesMax, numTiles, numTilings);

		numTiles = getConfig().getInt("actionTiles");
		numVariables = 4;
		numTilings = getConfig().getInt("actionTilings");
		double[] actionsMin = { -1, -1, -1, -1 };
		double[] actionsMax = { 1, 1, 1, 1 };

		initialiseActionTiling(numVariables, actionsMin, actionsMax, numTiles, numTilings);
		
		gaussianWidth = getConfig().getDouble("gaussian");
		System.out.println("Width=" + gaussianWidth);
	}

	/**
	 * A random action generated by a normal distribution about 0.
	 */
	@Override
	protected Action randomAction(Observation o) {
		Action a = new Action(0, 4);

		a.doubleArray[0] = randGenerator.nextGaussian() / gaussianWidth;
		a.doubleArray[1] = randGenerator.nextGaussian() / gaussianWidth;
		a.doubleArray[2] = randGenerator.nextGaussian() / gaussianWidth;
		a.doubleArray[3] = randGenerator.nextGaussian() / gaussianWidth;

		for (int i = 0; i < 4; i++) {
			if (a.doubleArray[i] > 1) {
				a.doubleArray[i] = 1;
			} else if (a.doubleArray[i] < -1) {
				a.doubleArray[i] = -1;
			}
		}
		return a;

	}

	public static void main(String[] args) {
		AgentLoader L = new AgentLoader(new HelicopterAgentTileCodedQGaussian());
		L.run();
	}
}
