include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedQGaussian -cp $(classPath) HelicopterAgentTileCodedQGaussian.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedQGaussian/*
