RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 8 -d ../../../bin/HelicopterAgentQ -cp $(RLVizPath)/RLVizLib.jar:../../../../../JavaRLGlueCodec.jar HelicopterAgentQ.java ../HelicopterQTable.java 


clean:
	rm -Rf ../../../bin/HelicopterAgentQ/*
