RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 5 -d ../../../bin/HelicopterAgentQ -cp $(RLVizPath)/RLVizLib.jar HelicopterAgentQ.java ../QTable.java


clean:
	rm -Rf ../../../bin/HelicopterAgentQ/*
