include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedSARSAGuided -cp $(classPath) HelicopterAgentTileCodedSARSAGuided.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedSARSAGuided/*
