include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedQGuided -cp $(classPath) HelicopterAgentTileCodedQGuided.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedQGuided/*
