include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedEligibilitySARSA -cp $(classPath) HelicopterAgentTileCodedEligibilitySARSA.java EligibilityQTable.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedEligibilitySARSA/*
