include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedSARSA -cp $(classPath) HelicopterAgentTileCodedSARSA.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedSARSA/*
