RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 8 -d ../../../bin/HelicopterAgentSARSADiscretised -cp $(RLVizPath)/RLVizLib.jar:../../../../../JavaRLGlueCodec.jar HelicopterAgentSARSADiscretised.java ../HelicopterAgentSARSA/HelicopterAgentSARSA.java ../HelicopterQTable.java


clean:
	rm -Rf ../../../bin/HelicopterAgentSARSADiscretised/*
