RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 5 -d ../../../bin/HelicopterAgentJava -cp $(RLVizPath)/RLVizLib.jar HelicopterAgent.java 

clean:
	rm -Rf ../../../bin/HelicopterAgentJava/*
