RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 8 -d ../../../bin/HelicopterAgentJava -cp $(RLVizPath)/RLVizLib.jar:../../../../../JavaRLGlueCodec.jar HelicopterAgent.java

clean:
	rm -Rf ../../../bin/HelicopterAgentJava/*
