RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 8 -d ../../../bin/HelicopterAgentSARSA -cp $(RLVizPath)/RLVizLib.jar HelicopterAgentSARSA.java ../HelicopterQTable.java


clean:
	rm -Rf ../../../bin/HelicopterAgentSARSA/*
