RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 5 -d ../../../bin/HelicopterAgentTileCodedSARSAGuided -cp $(RLVizPath)/RLVizLib.jar -cp ../../../../../YORLL.jar HelicopterAgentTileCodedSARSAGuided.java ../TileCodedHelicopterState.java ../TileCodedHelicopterAction.java ../TileCodeQTableInterface.java ../TileCodeQTableFlat.java ../TileCodeQTable.java ../Tile.java ../TileCoding.java


clean:
	rm -Rf ../../../bin/HelicopterAgentTileCodedSARSAGuided/*
