include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedQ -cp $(classPath) HelicopterAgentTileCodedQ.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedQ/*
