RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 8 -d ../../../bin/HelicopterAgentHierarchicalTileCodedQ -cp $(RLVizPath)/RLVizLib.jar -cp ../../../../../YORLL.jar HelicopterAgentHierarchicalTileCodedQ.java ../TileCodedHelicopterState.java ../TileCodedHelicopterAction.java ../TileCodeQTable.java ../Tile.java ../TileCoding.java


clean:
	rm -Rf ../../../bin/HelicopterAgentHierarchicalTileCodedQ/*
