RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 5 -d ../../../bin/HelicopterAgentTileCodedQ -cp $(RLVizPath)/RLVizLib.jar -cp ../../../../../YORLL.jar HelicopterAgentTileCodedQ.java ../TileCodedHelicopterState.java ../TileCodedHelicopterAction.java ../TileCoding.java


clean:
	rm -Rf ../../../bin/HelicopterAgentTileCodedQ/*
