
	RLVizPath=../../system/libraries/rl-viz

	classPath = $(RLVizPath)/RLVizLib.jar:../../../../../../JavaRLGlueCodec.jar:../../../../../../YORLL.jar:../../../../../../koloboke-api-jdk8-0.6.8.jar ../*.java ../tilings/*.java


