RLVizPath = ../../system/libraries/rl-viz

all:
	javac -source 5 -d ../../../bin/HelicopterAgentTileCodedSARSAGaussian -cp $(RLVizPath)/RLVizLib.jar -cp ../../../../../YORLL.jar HelicopterAgentTileCodedSARSAGaussian.java ../TileCodedHelicopterState.java ../TileCodedHelicopterAction.java ../TileCodeQTableInterface.java ../TileCodeQTableFlat.java ../TileCodeQTable.java ../Tile.java ../TileCoding.java


clean:
	rm -Rf ../../../bin/HelicopterAgentTileCodedSARSAGaussian/*
