include ../Makefile.classPath

all:
	javac -source 8 -d ../../../../bin/HelicopterAgentTileCodedSARSAGaussian -cp $(classPath) HelicopterAgentTileCodedSARSAGaussian.java


clean:
	rm -Rf ../../../../bin/HelicopterAgentTileCodedSARSAGaussian/*
